# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ios-png-check}
  s.version = "1.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Andrey Subbotin"]
  s.date = %q{2011-12-20}
  s.default_executable = ["ios-png-check"]
  s.description = %q{A simple utility to check that your @2x iOS PNG assets targeting iPhone 4 are in a good shape}
  s.email = %q{andrey@subbotin.me}
  s.executables = ["ios-png-check"]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.markdown"
  ]
  s.files = [
    "CHANGELOG",
    "LICENSE",
    "README.markdown",
    "VERSION"
  ]
  s.homepage = %q{http://github.com/eploko/ios-png-check}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{iPhone 4 @2x assets made easy}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<escape>, [">= 0"])
    else
      s.add_dependency(%q<escape>, [">= 0"])
    end
  else
    s.add_dependency(%q<escape>, [">= 0"])
  end
end

